"""
CompanionConversation — One row per conversation session.
Source: Architecture doc §21 models/companion_conversation.py
        V2.2 Spec §12.2 (CompanionConversation model)

A session = one continuous conversation (one voice call or WhatsApp exchange).
compacted_summary is what Ring 2 loads for returning candidates instead of
replaying the full transcript.
"""

import uuid
from datetime import datetime
from typing import Optional

from sqlalchemy import DateTime, Integer, String, Text
from sqlalchemy.dialects.postgresql import JSON, UUID
from sqlalchemy.orm import Mapped, mapped_column

from backend.models.base import Base


class CompanionConversation(Base):
    __tablename__ = "companion_conversations"

    # ── Foreign key ───────────────────────────────────────────────────────────
    candidate_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), nullable=False, index=True
    )

    # ── Session metadata ──────────────────────────────────────────────────────
    # channel: "voice" | "whatsapp_text" | "whatsapp_voice_note"
    channel: Mapped[str] = mapped_column(String(30), nullable=False)
    started_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    ended_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    turn_count: Mapped[int] = mapped_column(Integer, default=0)
    relationship_stage_at_start: Mapped[int] = mapped_column(Integer, default=1)

    # ── Messages — full transcript with timestamps and feedback ────────────────
    # Structure: [ { "turn": 1, "user_message": "hi", "zia_response": "...",
    #   "active_skill": "career_guide", "timestamp": "2026-03-24T...",
    #   "feedback": null (or "up" or "down") }, ... ]
    # Populated on every turn, used to reconstruct conversation history for
    # returning candidates or for analytics/replay.
    messages: Mapped[list] = mapped_column(JSON, default=list)
    # Generated by compact_conversation async task after session ends.
    # ~200 words capturing: key facts, emotional arc, open threads, commitments.
    compacted_summary: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # ── Analytics ─────────────────────────────────────────────────────────────
    # skill_sequence: ["career_guide", "salary_navigator", "career_guide"]
    skill_sequence: Mapped[list] = mapped_column(JSON, default=list)
    # key_moments: [{"type": "counter_offer", "turn": 12, "summary": "..."}]
    key_moments: Mapped[list] = mapped_column(JSON, default=list)

    def __repr__(self) -> str:
        return (
            f"<CompanionConversation "
            f"candidate={self.candidate_id} "
            f"channel={self.channel} "
            f"turns={self.turn_count}>"
        )

    @property
    def is_active(self) -> bool:
        return self.ended_at is None

    @property
    def duration_minutes(self) -> Optional[float]:
        if self.ended_at and self.started_at:
            delta = self.ended_at - self.started_at
            return round(delta.total_seconds() / 60, 1)
        return None