"""add_messages_column_to_conversations

Revision ID: 826e8dcce26b
Revises: 9a85f354a8b4
Create Date: 2026-03-24 09:01:17.470087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '826e8dcce26b'
down_revision: Union[str, None] = '9a85f354a8b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companion_conversations', sa.Column('messages', sa.JSON(), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companion_conversations', 'messages')
    # ### end Alembic commands ###