"""initial_tables_v2

Revision ID: 98adfd72d46a
Revises: 
Create Date: 2026-03-23 03:49:35.399284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '98adfd72d46a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('behavioral_signal_log',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('signal_value', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavioral_signal_log_candidate_id'), 'behavioral_signal_log', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_behavioral_signal_log_conversation_id'), 'behavioral_signal_log', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_behavioral_signal_log_id'), 'behavioral_signal_log', ['id'], unique=False)
    op.create_index(op.f('ix_behavioral_signal_log_signal_type'), 'behavioral_signal_log', ['signal_type'], unique=False)
    op.create_table('candidate_identities',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('identifier_type', sa.String(length=20), nullable=False),
    sa.Column('identifier_value', sa.String(length=200), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_identities_candidate_id'), 'candidate_identities', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_identities_id'), 'candidate_identities', ['id'], unique=False)
    op.create_index(op.f('ix_candidate_identities_identifier_type'), 'candidate_identities', ['identifier_type'], unique=False)
    op.create_index(op.f('ix_candidate_identities_identifier_value'), 'candidate_identities', ['identifier_value'], unique=False)
    op.create_table('companion_conversations',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('relationship_stage_at_start', sa.Integer(), nullable=False),
    sa.Column('compacted_summary', sa.Text(), nullable=True),
    sa.Column('skill_sequence', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('key_moments', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companion_conversations_candidate_id'), 'companion_conversations', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_companion_conversations_id'), 'companion_conversations', ['id'], unique=False)
    op.create_table('companion_profiles',
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('current_role', sa.String(length=200), nullable=True),
    sa.Column('yoe', sa.Float(), nullable=True),
    sa.Column('tech_stack', sa.Text(), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('company_type', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('comp_current', sa.Integer(), nullable=True),
    sa.Column('comp_target', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Text(), nullable=True),
    sa.Column('relationship_stage', sa.Integer(), nullable=False),
    sa.Column('mixing_board_state', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('assessment_status', sa.String(length=20), nullable=False),
    sa.Column('nudge_count', sa.Integer(), nullable=False),
    sa.Column('nudge_last_declined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_interaction_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companion_profiles_id'), 'companion_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_companion_profiles_phone'), 'companion_profiles', ['phone'], unique=True)
    op.create_table('memories',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding_text', sa.Text(), nullable=True),
    sa.Column('surfaced_count', sa.Integer(), nullable=False),
    sa.Column('last_surfaced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memories_candidate_id'), 'memories', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_memories_category'), 'memories', ['category'], unique=False)
    op.create_index(op.f('ix_memories_id'), 'memories', ['id'], unique=False)
    op.create_table('opportunity_cards',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('role_title', sa.String(length=200), nullable=False),
    sa.Column('company_type', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('ctc_range_min', sa.Integer(), nullable=True),
    sa.Column('ctc_range_max', sa.Integer(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('match_reason', sa.Text(), nullable=True),
    sa.Column('shown_in_dashboard', sa.Boolean(), nullable=False),
    sa.Column('shown_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('candidate_response', sa.String(length=20), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sourced_from', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_cards_candidate_id'), 'opportunity_cards', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_opportunity_cards_id'), 'opportunity_cards', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunity_cards_id'), table_name='opportunity_cards')
    op.drop_index(op.f('ix_opportunity_cards_candidate_id'), table_name='opportunity_cards')
    op.drop_table('opportunity_cards')
    op.drop_index(op.f('ix_memories_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_category'), table_name='memories')
    op.drop_index(op.f('ix_memories_candidate_id'), table_name='memories')
    op.drop_table('memories')
    op.drop_index(op.f('ix_companion_profiles_phone'), table_name='companion_profiles')
    op.drop_index(op.f('ix_companion_profiles_id'), table_name='companion_profiles')
    op.drop_table('companion_profiles')
    op.drop_index(op.f('ix_companion_conversations_id'), table_name='companion_conversations')
    op.drop_index(op.f('ix_companion_conversations_candidate_id'), table_name='companion_conversations')
    op.drop_table('companion_conversations')
    op.drop_index(op.f('ix_candidate_identities_identifier_value'), table_name='candidate_identities')
    op.drop_index(op.f('ix_candidate_identities_identifier_type'), table_name='candidate_identities')
    op.drop_index(op.f('ix_candidate_identities_id'), table_name='candidate_identities')
    op.drop_index(op.f('ix_candidate_identities_candidate_id'), table_name='candidate_identities')
    op.drop_table('candidate_identities')
    op.drop_index(op.f('ix_behavioral_signal_log_signal_type'), table_name='behavioral_signal_log')
    op.drop_index(op.f('ix_behavioral_signal_log_id'), table_name='behavioral_signal_log')
    op.drop_index(op.f('ix_behavioral_signal_log_conversation_id'), table_name='behavioral_signal_log')
    op.drop_index(op.f('ix_behavioral_signal_log_candidate_id'), table_name='behavioral_signal_log')
    op.drop_table('behavioral_signal_log')
    # ### end Alembic commands ###