"""add conversation feedback and messages field

Revision ID: 9a85f354a8b4
Revises: 98adfd72d46a
Create Date: 2026-03-24 08:00:20.654382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9a85f354a8b4'
down_revision: Union[str, None] = '98adfd72d46a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_feedback',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('rating', sa.String(length=10), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_feedback_id'), 'conversation_feedback', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_feedback_session_id'), 'conversation_feedback', ['session_id'], unique=False)
    op.add_column('companion_conversations', sa.Column('messages', postgresql.JSON(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companion_conversations', 'messages')
    op.drop_index(op.f('ix_conversation_feedback_session_id'), table_name='conversation_feedback')
    op.drop_index(op.f('ix_conversation_feedback_id'), table_name='conversation_feedback')
    op.drop_table('conversation_feedback')
    # ### end Alembic commands ###